name: CI

on:
  push:
    branches: [ main, develop ]
    tags: [ '*' ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v4
      with:
        version: ^10.24
    - uses: actions/setup-node@v3
      with:
        node-version: '24'
        cache: 'pnpm'
    - run: pnpm install
    - run: pnpm run postinstall
    - run: pnpm test
